import {
  faFillDrip,
  faFolderOpen,
  faRulerVertical,
  faUsersGear,
} from '@fortawesome/free-solid-svg-icons';
import {
  AccountTreeOutlined,
  AssessmentOutlined,
  BusinessCenterOutlined,
  CardMembershipOutlined,
  ChecklistRtlOutlined,
  CorporateFareOutlined,
  CurrencyExchangeOutlined,
  DashboardCustomizeOutlined,
  EditAttributesOutlined,
  FormatListNumberedOutlined,
  HandshakeOutlined,
  Inventory2Outlined,
  LocalGasStation,
  ManageAccountsOutlined,
  PeopleAltOutlined,
  PointOfSaleOutlined,
  QrCode,
  ReceiptOutlined,
  RequestQuoteOutlined,
  RocketLaunchOutlined,
  RoomPreferencesOutlined,
  ShareOutlined,
  ShoppingCartCheckout,
  ShoppingCartOutlined,
  SmsOutlined,
  StoreOutlined,
  StraightenOutlined,
  TroubleshootOutlined,
  TuneOutlined,
  VerifiedOutlined,
  ViewAgendaOutlined,
} from '@mui/icons-material';

export const ICONS = {
  quickLaunch: RocketLaunchOutlined,
  dashboard: DashboardCustomizeOutlined,
  requisitions: FormatListNumberedOutlined,
  approvals: ChecklistRtlOutlined,
  approvedPayments: VerifiedOutlined,
  approvedPurchases: ShoppingCartCheckout,
  counter: PointOfSaleOutlined,
  proforma: RequestQuoteOutlined,
  projects: ViewAgendaOutlined,
  transactions: ReceiptOutlined,
  purchases: ShoppingCartOutlined,
  consumptions: faFillDrip,
  barcharts: AssessmentOutlined,
  organizations: CorporateFareOutlined,
  batches: QrCode,
  invitations: ShareOutlined,
  stakeholders: HandshakeOutlined,
  currencies: CurrencyExchangeOutlined,
  measurement_units: StraightenOutlined,
  filesShelf: faFolderOpen,
  usersManagement: ManageAccountsOutlined,
  reports: AssessmentOutlined,
  product_categories: Inventory2Outlined,
  products: Inventory2Outlined,
  manufacturingMasters: TuneOutlined,
  outlets: StoreOutlined,
  settings: StoreOutlined,
  nextSMS: SmsOutlined,
  troubleshooting: TroubleshootOutlined,
  subscriptions: CardMembershipOutlined,
  salesShifts: LocalGasStation,
  dippings: faRulerVertical,
  fuelMasters: RoomPreferencesOutlined,
  prosAfricans: faUsersGear,
  editAttributes: EditAttributesOutlined,
  accountTree: AccountTreeOutlined,
  employees: PeopleAltOutlined,
  businessCenter: BusinessCenterOutlined,
} as const;

export type IconName = keyof typeof ICONS;
