export const PERMISSIONS = {
  // Accounts & Finance
  ACCOUNTS_MASTERS_CREATE: 'AccountsMasters:Create',
  ACCOUNTS_MASTERS_DELETE: 'AccountsMasters:Delete',
  ACCOUNTS_MASTERS_EDIT: 'AccountsMasters:Edit',
  ACCOUNTS_MASTERS_READ: 'AccountsMasters:Read',
  ACCOUNTS_REPORTS: 'Accounts:Reports',
  ACCOUNTS_TRANSACTIONS_BACKDATE: 'AccountsTransactions:BackDate',
  ACCOUNTS_TRANSACTIONS_CREATE: 'AccountsTransactions:Create',
  ACCOUNTS_TRANSACTIONS_DELETE: 'AccountsTransactions:Delete',
  ACCOUNTS_TRANSACTIONS_EDIT: 'AccountsTransactions:Edit',
  ACCOUNTS_TRANSACTIONS_POSTDATE: 'AccountsTransactions:PostDate',
  ACCOUNTS_TRANSACTIONS_READ: 'AccountsTransactions:Read',
  COST_CENTERS_ALL: 'CostCenters:All',
  FUND_TRANSFERS_BACKDATE: 'FundTransfers:BackDate',
  FUND_TRANSFERS_CREATE: 'FundTransfers:Create',
  FUND_TRANSFERS_DELETE: 'FundTransfers:Delete',
  FUND_TRANSFERS_EDIT: 'FundTransfers:Edit',
  FUND_TRANSFERS_POSTDATE: 'FundTransfers:PostDate',
  FUND_TRANSFERS_READ: 'FundTransfers:Read',
  JOURNAL_VOUCHERS_BACKDATE: 'JournalVouchers:BackDate',
  JOURNAL_VOUCHERS_CREATE: 'JournalVouchers:Create',
  JOURNAL_VOUCHERS_DELETE: 'JournalVouchers:Delete',
  JOURNAL_VOUCHERS_EDIT: 'JournalVouchers:Edit',
  JOURNAL_VOUCHERS_POSTDATE: 'JournalVouchers:PostDate',
  JOURNAL_VOUCHERS_READ: 'JournalVouchers:Read',
  PAYMENTS_BACKDATE: 'Payments:BackDate',
  PAYMENTS_CREATE: 'Payments:Create',
  PAYMENTS_DELETE: 'Payments:Delete',
  PAYMENTS_EDIT: 'Payments:Edit',
  PAYMENTS_POSTDATE: 'Payments:PostDate',
  PAYMENTS_READ: 'Payments:Read',
  RECEIPTS_BACKDATE: 'Receipts:BackDate',
  RECEIPTS_CREATE: 'Receipts:Create',
  RECEIPTS_DELETE: 'Receipts:Delete',
  RECEIPTS_EDIT: 'Receipts:Edit',
  RECEIPTS_POSTDATE: 'Receipts:PostDate',
  RECEIPTS_READ: 'Receipts:Read',

  BUDGETS_CREATE: 'Budgets:Create',
  BUDGETS_EDIT: 'Budgets:Edit',
  BUDGETS_READ: 'Budgets:Read',
  BUDGETS_DELETE: 'Budgets:Delete',

  // Process Approval
  APPROVAL_BACKDATE: 'Approvals:BackDate',
  APPROVAL_CHAINS_CREATE: 'ApprovalChains:Create',
  APPROVAL_CHAINS_DEACTIVATE: 'ApprovalChains:Deactivate',
  APPROVAL_CHAINS_EDIT: 'ApprovalChains:Edit',
  APPROVAL_CHAINS_READ: 'ApprovalChains:Read',
  APPROVAL_POSTDATE: 'Approvals:PostDate',

  APPROVED_REQUISITIONS_PAY: 'ApprovedRequisitions:Pay',
  APPROVED_REQUISITIONS_PURCHASE: 'ApprovedRequisitions:Purchase',
  APPROVED_REQUISITIONS_READ: 'ApprovedRequisitions:Read',
  IMPREST_RETIREMENTS_READ: 'ImprestRetirements:Read',
  IMPREST_RETIREMENT_APPROVALS_DELETE_ANY:
    'ImprestRetirementApprovals:DeleteAny',
  REQUISITIONS_BACKDATE: 'Requisitions:BackDate',
  REQUISITIONS_CREATE: 'Requisitions:Create',
  REQUISITIONS_DELETE: 'Requisitions:Delete',
  REQUISITIONS_EDIT: 'Requisitions:Edit',
  REQUISITIONS_POSTDATE: 'Requisitions:PostDate',
  REQUISITIONS_READ: 'Requisitions:Read',
  REQUISITIONS_APPROVALS_DELETE_ANY: 'RequisitionApprovals:DeleteAny',

  // Point Of Sale (POS)
  OUTLETS_EDIT: 'Outlets:Edit',
  OUTLETS_READ: 'Outlets:Read',
  POS_SETTINGS: 'POS:Settings',
  PRICE_LISTS_BACKDATE: 'PriceLists:BackDate',
  PRICE_LISTS_CREATE: 'PriceLists:Create',
  PRICE_LISTS_DELETE: 'PriceLists:Delete',
  PRICE_LISTS_EDIT: 'PriceLists:Edit',
  PRICE_LISTS_POSTDATE: 'PriceLists:PostDate',
  PRICE_LISTS_READ: 'PriceLists:Read',
  PROFORMA_INVOICES_BACKDATE: 'ProformaInvoices:BackDate',
  PROFORMA_INVOICES_CREATE: 'ProformaInvoices:Create',
  PROFORMA_INVOICES_DELETE: 'ProformaInvoices:Delete',
  PROFORMA_INVOICES_EDIT: 'ProformaInvoices:Edit',
  PROFORMA_INVOICES_POSTDATE: 'ProformaInvoices:PostDate',
  PROFORMA_INVOICES_READ: 'ProformaInvoices:Read',
  SALES_BACKDATE: 'Sales:BackDate',
  SALES_COMPLETE: 'Sales:Complete',
  SALES_CREATE: 'Sales:Create',
  SALES_DELETE: 'Sales:Delete',
  SALES_DISPATCH: 'Sales:Dispatch',
  SALES_DISPATCH_BACKDATE: 'SalesDispatch:BackDate',
  SALES_DISPATCH_DELETE: 'SalesDispatch:Delete',
  SALES_DISPATCH_EDIT: 'SalesDispatch:Edit',
  SALES_DISPATCH_OLD_SALES: 'Sales:DispatchOldSales',
  SALES_DISPATCH_NOT_FULLY_PAID: 'Sales:DispatchNotFullyPaid',
  SALES_DISPATCH_POSTDATE: 'SalesDispatch:PostDate',
  SALES_EDIT: 'Sales:Edit',
  SALES_MODIFY_COMPLETED: 'Sales:ModifyCompleted',
  SALES_POSTDATE: 'Sales:PostDate',
  SALES_READ: 'Sales:Read',
  SALES_REPORTS: 'Sales:Reports',
  SALES_VIEW_ALL: 'Sales:ViewAll',

  // Fuel Station
  FUEL_SALES_SHIFTS_CLOSE: 'FuelSalesShifts:Close',
  FUEL_SALES_SHIFTS_CREATE: 'FuelSalesShifts:Create',
  FUEL_SALES_SHIFTS_DELETE: 'FuelSalesShifts:Delete',
  FUEL_SALES_SHIFTS_READ: 'FuelSalesShifts:Read',
  FUEL_SALES_SHIFTS_UPDATE: 'FuelSalesShifts:Update',
  FUEL_SALES_SHIFTS_BACKDATE: 'FuelSalesShifts:BackDate',
  FUEL_STATIONS_CREATE: 'FuelStations:Create',
  FUEL_STATIONS_DELETE: 'FuelStations:Delete',
  FUEL_STATIONS_READ: 'FuelStations:Read',
  FUEL_STATIONS_UPDATE: 'FuelStations:Update',

  // Procurement & Supply
  INVENTORY_CONSUMPTIONS_BACKDATE: 'InventoryConsumptions:BackDate',
  INVENTORY_CONSUMPTIONS_CREATE: 'InventoryConsumptions:Create',
  INVENTORY_CONSUMPTIONS_DELETE: 'InventoryConsumptions:Delete',
  INVENTORY_CONSUMPTIONS_EDIT: 'InventoryConsumptions:Edit',
  INVENTORY_CONSUMPTIONS_POSTDATE: 'InventoryConsumptions:PostDate',
  INVENTORY_CONSUMPTIONS_READ: 'InventoryConsumptions:Read',
  INVENTORY_TRANSFERS_BACKDATE: 'InventoryTransfers:BackDate',
  INVENTORY_TRANSFERS_CREATE: 'InventoryTransfers:Create',
  INVENTORY_TRANSFERS_DELETE: 'InventoryTransfers:Delete',
  INVENTORY_TRANSFERS_EDIT: 'InventoryTransfers:Edit',
  INVENTORY_TRANSFERS_POSTDATE: 'InventoryTransfers:PostDate',
  INVENTORY_TRANSFERS_READ: 'InventoryTransfers:Read',
  PRODUCT_CATEGORIES_CREATE: 'ProductCategories:Create',
  PRODUCT_CATEGORIES_DELETE: 'ProductCategories:Delete',
  PRODUCT_CATEGORIES_EDIT: 'ProductCategories:Edit',
  PRODUCT_CATEGORIES_READ: 'ProductCategories:Read',
  PRODUCTS_CREATE: 'Products:Create',
  PRODUCTS_DELETE: 'Products:Delete',
  PRODUCTS_EDIT: 'Products:Edit',
  PRODUCTS_READ: 'Products:Read',
  PURCHASES_BACKDATE: 'Purchases:BackDate',
  PURCHASES_COMPLETE: 'Purchases:Complete',
  PURCHASES_CREATE: 'Purchases:Create',
  PURCHASES_DELETE: 'Purchases:Delete',
  PURCHASES_EDIT: 'Purchases:Edit',
  PURCHASES_POSTDATE: 'Purchases:PostDate',
  PURCHASES_READ: 'Purchases:Read',
  PURCHASES_RECEIVE: 'Purchases:Receive',
  PURCHASES_REPORTS: 'Purchases:Reports',
  PURCHASES_UNRECEIVE: 'Purchases:Unreceive',
  RFQS_CREATE: 'RFQs:Create',
  RFQS_DELETE: 'RFQs:Delete',
  RFQS_EDIT: 'RFQs:Edit',
  RFQS_READ: 'RFQs:Read',
  STAKEHOLDERS_CREATE: 'Stakeholders:Create',
  STAKEHOLDERS_DELETE: 'Stakeholders:Delete',
  STAKEHOLDERS_EDIT: 'Stakeholders:Edit',
  STAKEHOLDERS_READ: 'Stakeholders:Read',
  STOCK_ADJUSTMENTS_CREATE: 'StockAdjustments:Create',
  STOCK_ADJUSTMENTS_DELETE: 'StockAdjustments:Delete',
  STOCK_ADJUSTMENTS_EDIT: 'StockAdjustments:Edit',
  STOCK_ADJUSTMENTS_READ: 'StockAdjustments:Read',
  STORES_CREATE: 'Stores:Create',
  STORES_DELETE: 'Stores:Delete',
  STORES_EDIT: 'Stores:Edit',
  STORES_READ: 'Stores:Read',
  STORES_REPORTS: 'Stores:Reports',

  // human resources
  EMPLOYEES_CREATE: 'Employees:Create',
  EMPLOYEES_READ: 'Employees:Read',
  EMPLOYEES_UPDATE: 'Employees:Update',
  EMPLOYEES_DELETE: 'Employees:Delete',
  PAYROLLRUNS_CREATE: 'PayrollRuns:Create',
  PAYROLL_READ: 'Payroll:Read',
  LOANS_READ: 'Loans:Read',
  LOANS_CREATE: 'Loans:Create',
  LOANS_EDIT: 'Loans:Edit',
  LOANS_DELETE: 'Loans:Delete',
  LEAVE_ALLOCATIONS_READ: 'LeaveAllocations:Read',
  LEAVE_ALLOCATIONS_CREATE: 'LeaveAllocations:Create',
  LEAVE_ALLOCATIONS_EDIT: 'LeaveAllocations:Edit',
  LEAVE_ALLOCATIONS_DELETE: 'LeaveAllocations:Delete',
  LEAVE_REQUESTS_READ: 'LeaveRequests:Read',
  LEAVE_REQUESTS_CREATE: 'LeaveRequests:Create',
  LEAVE_REQUESTS_EDIT: 'LeaveRequests:Edit',
  LEAVE_REQUESTS_DELETE: 'LeaveRequests:Delete',

  // Manufacturing & Processing
  BOM_CREATE: 'BOM:Create',
  BOM_DELETE: 'BOM:Delete',
  BOM_EDIT: 'BOM:Edit',
  BOM_READ: 'BOM:Read',
  PRODUCTION_BATCHES_CREATE: 'ProductionBatches:Create',
  PRODUCTION_BATCHES_DELETE: 'ProductionBatches:Delete',
  PRODUCTION_BATCHES_EDIT: 'ProductionBatches:Update',
  PRODUCTION_BATCHES_READ: 'ProductionBatches:Read',
  WORK_CENTERS_CREATE: 'WorkCenters:Create',
  WORK_CENTERS_DELETE: 'WorkCenters:Delete',
  WORK_CENTERS_EDIT: 'WorkCenters:Edit',
  WORK_CENTERS_READ: 'WorkCenters:Read',
  MANUFACTURING_ORDERS_CREATE: 'ManufacturingOrders:Create',
  MANUFACTURING_ORDERS_DELETE: 'ManufacturingOrders:Delete',
  MANUFACTURING_ORDERS_EDIT: 'ManufacturingOrders:Edit',
  MANUFACTURING_ORDERS_READ: 'ManufacturingOrders:Read',

  // Project Management
  PROJECT_CATEGORIES_CREATE: 'ProjectCategories:Create',
  PROJECT_CATEGORIES_DELETE: 'ProjectCategories:Delete',
  PROJECT_CATEGORIES_EDIT: 'ProjectCategories:Edit',
  PROJECT_CATEGORIES_READ: 'ProjectCategories:Read',

  PROJECTS_CREATE: 'Projects:Create',
  PROJECTS_DELETE: 'Projects:Delete',
  PROJECTS_EDIT: 'Projects:Edit',
  PROJECTS_READ: 'Projects:Read',

  PROJECT_SUBCONTRACTS_CREATE: 'ProjectSubcontracts:Create',
  PROJECT_SUBCONTRACTS_EDIT: 'ProjectSubcontracts:Edit',
  PROJECT_SUBCONTRACTS_DELETE: 'ProjectSubcontracts:Delete',

  PROJECTS_MANAGE_TEAM: 'Projects:ManageTeam',

  PROJECT_CLAIMS_CREATE: 'ProjectClaims:Create',
  PROJECT_CLAIMS_UPDATE: 'ProjectClaims:Update',
  PROJECT_CLAIMS_DELETE: 'ProjectClaims:Delete',

  // Shared / Organization / Platform
  AUDIT_READ: 'Audit:Read',
  FILES_SHELF_BROWSE: 'FilesShelf:Browse',
  MEASUREMENT_UNITS_CREATE: 'MeasurementUnits:Create',
  MEASUREMENT_UNITS_DELETE: 'MeasurementUnits:Delete',
  MEASUREMENT_UNITS_EDIT: 'MeasurementUnits:Edit',
  MEASUREMENT_UNITS_READ: 'MeasurementUnits:Read',
  ORGANIZATION_PROFILE: 'Organization:Profile',
  ORGANIZATION_UPDATE: 'Organization:Update',
  ROLES_ADD: 'Roles:Add',
  ROLES_UPDATE: 'Roles:Update',
  SUBSCRIPTIONS_MANAGE: 'Subscriptions:Manage',
  USERS_INVITE: 'Users:Invite',
  USERS_MANAGE: 'Users:Manage',
};
