// Static menu structure for client-side global search (no server-only imports)
// Add or update as needed to match your sidebar/menu

export const staticMenuItems = [
  { label: 'Dashboard', uri: '/en-US/dashboard' },
  { label: 'Requisitions', uri: '/en-US/requisitions' },
  { label: 'Approvals', uri: '/en-US/requisition-approvals' },
  { label: 'Approval Chains', uri: '/en-US/approval-chains' },
  { label: 'Sales Counter', uri: '/en-US/pos/sales-counters' },
  { label: 'Proforma Invoices', uri: '/en-US/pos/proformas' },
  { label: 'POS Reports', uri: '/en-US/pos/reports' },
  { label: 'Outlets', uri: '/en-US/pos/outlets' },
  { label: 'POS Price Lists', uri: '/en-US/pos/price_lists' },
  { label: 'POS Settings', uri: '/en-US/pos/pos-settings' },
  { label: 'Sales Shifts', uri: '/en-US/fuelStations/salesShifts' },
  { label: 'Dippings', uri: '/en-US/fuelStations/dippings' },
  { label: 'Fuel Reports', uri: '/en-US/fuelStations/reports' },
  { label: 'Stations', uri: '/en-US/fuelStations/stations' },
  { label: 'Fuel Price Lists', uri: '/en-US/fuelStations/price_lists' },
  { label: 'Production Batches', uri: '/en-US/manufacturing/batches' },
  { label: 'BOMs', uri: '/en-US/manufacturing/boms' },
  { label: 'Projects', uri: '/en-US/projectManagement/projects' },
  { label: 'Project Categories', uri: '/en-US/projectManagement/projectCategories' },
  { label: 'Approved Payments', uri: '/en-US/accounts/approvedPayments' },
  { label: 'Transactions', uri: '/en-US/accounts/transactions' },
  { label: 'Accounts Reports', uri: '/en-US/accounts/reports' },
  { label: 'Budgets', uri: '/en-US/accounts/budgets' },
  { label: 'Ledger Groups', uri: '/en-US/accounts/ledger_groups' },
  { label: 'Ledgers', uri: '/en-US/accounts/ledgers' },
  { label: 'User Ledgers', uri: '/en-US/accounts/user-ledgers' },
  { label: 'Cost Centers', uri: '/en-US/cost_centers' },
  { label: 'Approved Purchases', uri: '/en-US/procurement/approvedPurchases' },
  { label: 'Purchases', uri: '/en-US/procurement/purchases' },
  { label: 'Consumptions', uri: '/en-US/procurement/consumptions' },
  { label: 'Procurement Reports', uri: '/en-US/procurement/reports' },
  { label: 'Product Categories', uri: '/en-US/procurement/product_categories' },
  { label: 'Products', uri: '/en-US/procurement/products' },
  { label: 'Stores', uri: '/en-US/procurement/stores' },
  { label: 'Files Shelf', uri: '/en-US/filesShelf' },
  { label: 'Stakeholders', uri: '/en-US/masters/stakeholders' },
  { label: 'Currencies', uri: '/en-US/masters/currencies' },
  { label: 'Measurement Units', uri: '/en-US/masters/measurement_units' },
  { label: 'ProsAfricans', uri: '/en-US/prosControl/prosAfricans' },
  { label: 'Subscriptions', uri: '/en-US/prosControl/subscriptions' },
  { label: 'Troubleshooting', uri: '/en-US/prosControl/troubleshooting' },
  { label: 'Users Management', uri: '/en-US/prosControl/usersManagement' },
  { label: 'SMS', uri: '/en-US/prosControl/nextSMS' },
  { label: 'Organizations', uri: '/en-US/organizations' },
  { label: 'Invitations', uri: '/en-US/invitations' },
  // Human Resources
  { label: 'Employees', uri: '/en-US/humanResources/employees' },
  { label: 'Leave Requests', uri: '/en-US/humanResources/leave-requests' },
  { label: 'Payroll Periods', uri: '/en-US/humanResources/payroll' },
  { label: 'Departments', uri: '/en-US/humanResources/departments' },
  { label: 'Designations', uri: '/en-US/humanResources/designations' },
  { label: 'Leave Types', uri: '/en-US/humanResources/leave_types' },
  { label: 'Allowance Types', uri: '/en-US/humanResources/allowance-types' },
  { label: 'Deduction Types', uri: '/en-US/humanResources/deduction-types' },
  { label: 'Employer Contribution Types', uri: '/en-US/humanResources/employer-contribution-types' },
  { label: 'PAYE Tax Bands', uri: '/en-US/humanResources/paye-tax-bands' },
];
